export default {
  AUTH_PENDING: 'AUTH_PENDING',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',

  AUTH_LOGOUT_PENDING: 'AUTH_LOGOUT_PENDING',
  AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
};
